/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import util from '@ohos.util';

export interface Base64Interface {
  encode(str: Uint8Array | string): string;

  decode(str: string): Uint8Array
}

export class HOSBase64 implements Base64Interface {
  private base64Util = new util.Base64();

  encode(str: Uint8Array): string {
    //todo
    let result = this.base64Util.encodeToStringSync(str);
    return result;
  }

  decode(str: string): Uint8Array {
    //todo
    return this.base64Util.decodeSync(str);
  }
}